spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 344249881177-459i3i5kdh20qdseg3hs03hako4c4uo4.apps.googleusercontent.com
            client-secret: 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

scope:
  - openid
  - profile
  - email
provider:
  google:
    authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
    token-uri: https://oauth2.googleapis.com/token
    user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo